// <auto-generated>
//     This code was generated by the .NET ToolStrip Customizer.
//     http://toolstripcustomizer.codeplex.com/
//
// (Most of it, anyway, I (mash) had to add the CustomMenuRenderer bit ;)
//
// </auto-generated>

using System.Drawing;
using System.Windows.Forms;

namespace MashWin {
    public class CustomMenuRenderer : ToolStripProfessionalRenderer {
        public CustomMenuRenderer()
            : base(new MashMenuColors()) {
            }

        internal class MashMenuColors : ProfessionalColorTable {
            public override Color ButtonSelectedHighlight {
                get {
                    return ButtonSelectedGradientMiddle;
                    }
                }
            public override Color ButtonSelectedHighlightBorder {
                get {
                    return ButtonSelectedBorder;
                    }
                }
            public override Color ButtonPressedHighlight {
                get {
                    return ButtonPressedGradientMiddle;
                    }
                }
            public override Color ButtonPressedHighlightBorder {
                get {
                    return ButtonPressedBorder;
                    }
                }
            public override Color ButtonCheckedHighlight {
                get {
                    return ButtonCheckedGradientMiddle;
                    }
                }
            public override Color ButtonCheckedHighlightBorder {
                get {
                    return ButtonSelectedBorder;
                    }
                }
            public override Color ButtonPressedBorder {
                get {
                    return ButtonSelectedBorder;
                    }
                }
            public override Color ButtonSelectedBorder {
                get {
                    return Color.FromName("Highlight");
                    }
                }
            public override Color ButtonCheckedGradientBegin {
                get {
                    return Color.FromArgb(0, 0, 0, 0);
                    }
                }
            public override Color ButtonCheckedGradientMiddle {
                get {
                    return Color.FromArgb(0, 0, 0, 0);
                    }
                }
            public override Color ButtonCheckedGradientEnd {
                get {
                    return Color.FromArgb(0, 0, 0, 0);
                    }
                }
            public override Color ButtonSelectedGradientBegin {
                get {
                    return Color.FromArgb(255, 32, 32, 32);
                    }
                }
            public override Color ButtonSelectedGradientMiddle {
                get {
                    return Color.FromArgb(255, 0, 100, 120);
                    }
                }
            public override Color ButtonSelectedGradientEnd {
                get {
                    return Color.FromArgb(255, 0, 223, 223);
                    }
                }
            public override Color ButtonPressedGradientBegin {
                get {
                    return Color.FromArgb(255, 153, 204, 255);
                    }
                }
            public override Color ButtonPressedGradientMiddle {
                get {
                    return Color.FromArgb(255, 153, 204, 255);
                    }
                }
            public override Color ButtonPressedGradientEnd {
                get {
                    return Color.FromArgb(255, 153, 204, 255);
                    }
                }
            public override Color CheckBackground {
                get {
                    return Color.FromArgb(255, 196, 225, 255);
                    }
                }
            public override Color CheckSelectedBackground {
                get {
                    return Color.FromArgb(255, 153, 204, 255);
                    }
                }
            public override Color CheckPressedBackground {
                get {
                    return Color.FromArgb(255, 153, 204, 255);
                    }
                }
            public override Color GripDark {
                get {
                    return Color.FromArgb(255, 184, 184, 184);
                    }
                }
            public override Color GripLight {
                get {
                    return Color.FromArgb(255, 0, 100, 100);
                    }
                }
            public override Color ImageMarginGradientBegin {
                get {
                    return Color.FromArgb(255, 32, 32, 32);
                    }
                }
            public override Color ImageMarginGradientMiddle {
                get {
                    return Color.FromArgb(255, 32, 32, 32);
                    }
                }
            public override Color ImageMarginGradientEnd {
                get {
                    return Color.FromArgb(255, 32, 32, 32);
                    }
                }
            public override Color ImageMarginRevealedGradientBegin {
                get {
                    return Color.FromArgb(255, 32, 32, 32);
                    }
                }
            public override Color ImageMarginRevealedGradientMiddle {
                get {
                    return Color.FromArgb(255, 255, 6, 255);
                    }
                }
            public override Color ImageMarginRevealedGradientEnd {
                get {
                    return Color.FromArgb(255, 255, 6, 255);
                    }
                }
            public override Color MenuStripGradientBegin {
                get {
                    return Color.FromArgb(255, 32, 32, 32);
                    }
                }
            public override Color MenuStripGradientEnd {
                get {
                    return Color.FromArgb(255, 32, 32, 32);
                    }
                }
            public override Color MenuItemSelected {
                get {
                    return Color.FromArgb(255, 96, 96, 96);
                    }
                }
            public override Color MenuItemBorder {
                get {
                    return Color.FromArgb(255, 0, 213, 213);
                    }
                }
            public override Color MenuBorder {
                get {
                    return Color.FromArgb(255, 0, 174, 174);
                    }
                }
            public override Color MenuItemSelectedGradientBegin {
                get {
                    return Color.FromArgb(255, 0, 62, 62);
                    }
                }
            public override Color MenuItemSelectedGradientEnd {
                get {
                    return Color.FromArgb(255, 0, 100, 100);
                    }
                }
            public override Color MenuItemPressedGradientBegin {
                get {
                    return Color.FromArgb(255, 0, 62, 62);
                    }
                }
            public override Color MenuItemPressedGradientMiddle {
                get {
                    return Color.FromArgb(255, 0, 100, 100);
                    }
                }
            public override Color MenuItemPressedGradientEnd {
                get {
                    return Color.FromArgb(255, 0, 100, 100);
                    }
                }
            public override Color RaftingContainerGradientBegin {
                get {
                    return Color.FromArgb(255, 0, 200, 200);
                    }
                }
            public override Color RaftingContainerGradientEnd {
                get {
                    return Color.FromArgb(255, 0, 200, 200);
                    }
                }
            public override Color SeparatorDark {
                get {
                    return Color.FromArgb(255, 0, 200, 200);
                    }
                }
            public override Color SeparatorLight {
                get {
                    return Color.FromArgb(255, 0, 200, 200);
                    }
                }
            public override Color StatusStripGradientBegin {
                get {
                    return Color.FromArgb(255, 255, 6, 255);
                    }
                }
            public override Color StatusStripGradientEnd {
                get {
                    return Color.FromArgb(255, 255, 6, 255);
                    }
                }
            public override Color ToolStripBorder {
                get {
                    return Color.FromArgb(255, 0, 200, 200);
                    }
                }
            public override Color ToolStripDropDownBackground {
                get {
                    return Color.FromArgb(255, 32, 32, 32);
                    }
                }
            public override Color ToolStripGradientBegin {
                get {
                    return Color.FromArgb(255, 252, 252, 252);
                    }
                }
            public override Color ToolStripGradientMiddle {
                get {
                    return Color.FromArgb(255, 248, 248, 248);
                    }
                }
            public override Color ToolStripGradientEnd {
                get {
                    return Color.FromName("ButtonFace");
                    }
                }
            public override Color ToolStripContentPanelGradientBegin {
                get {
                    return Color.FromName("ButtonFace");
                    }
                }
            public override Color ToolStripContentPanelGradientEnd {
                get {
                    return Color.FromArgb(255, 252, 252, 252);
                    }
                }
            public override Color ToolStripPanelGradientBegin {
                get {
                    return Color.FromName("ButtonFace");
                    }
                }
            public override Color ToolStripPanelGradientEnd {
                get {
                    return Color.FromArgb(255, 252, 252, 252);
                    }
                }
            public override Color OverflowButtonGradientBegin {
                get {
                    return Color.FromArgb(255, 245, 245, 245);
                    }
                }
            public override Color OverflowButtonGradientMiddle {
                get {
                    return Color.FromArgb(255, 242, 242, 242);
                    }
                }
            public override Color OverflowButtonGradientEnd {
                get {
                    return Color.FromName("ButtonShadow");
                    }
                }
            }
        }
    }